name: release
# Run this job whenever a push is made that starts with 'v'
on:
  push:
    tags:
      - 'v*'
jobs:
    release:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Create Client Modpack
          working-directory: modpack
          run: zip -r client.zip *
        - name: Download Mods from Curseforge
          working-directory: modpack
          run: python3 -c 'import json; print("\n".join(["https://www.curseforge.com/api/v1/mods/%i/files/%i/download" % (f["projectID"], f["fileID"]) for f in json.load(open("manifest.json", "r"))["files"] if f["required"]]))' | wget -q -i - -P mods/ --content-disposition --show-progress
        - name: Setup appropriate folder name for server pack
          run: mv modpack/overrides modpack/config
        - name: Create Server pack
          run: zip -r server.zip modpack/config modpack/mods
        - name: Create a Release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          with:
            files: |
              ops.json
              whitelist.json
              modpack/client.zip
              server.zip

